config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings do
    resources :orders, only: [:new, :create]
    resources :charges
  end
  root 'listings#index'

  get '/buying', to: 'charges#new'

  get 'pages/about'

  get 'pages/contact'

  get '/sales', to: 'orders#sales'

  get '/purchases', to: 'orders#purchases'

  get 'seller' => 'listings#seller'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :name, :description, :price, presence: true
  validates :price, numericality: {greater_than: 0}

  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  has_paper_trail
  validates :address, :city, :state, presence: true


  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_paper_trail_whodunnit
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: "Thanks for ordering!" }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_devise_error.html.erb
<% if @user.errors.any? %>
  <div id="card-alert" class="card red lighten-5">
    <div class="card-content red-text">
      <h5><%= pluralize(@user.errors.count, "error") %> prohibited this listing from being saved:</h5>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li style="padding-left: 30px; padding-bottom: 20px;"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
      <footer class="page-footer" style="background-color: #efefeb;">
        <div class="container">
          <div class="row">
            <div class="col l6 s12">
              <h5 class="black-text">Contact us</h5>
              <p class="black-text">jon.corrin@gmail.com</p>
            </div>
            <div class="col l4 offset-l2 s12">
              <h5 class="black-text">Social Media</h5>
              <ul>
                <li><a class="black-text" href="#!">Facebook</a></li>
                <li><a class="black-text" href="#!">Twitter</a></li>
                <li><a class="black-text" href="#!">Github</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright" style="color: black;">
          <div class="container">
            © 2017 Jon Corrin
          </div>
        </div>
      </footer>

app/views/layouts/_header.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
<title>Sell Stuff</title>

<!-- CSS  -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
<link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'https://js.stripe.com/v2/' %>
<%= csrf_meta_tags %>
<%= tag :meta, name: 'stripe-key', content: ENV['STRIPE_PUBLIC_KEY'] %>

app/views/layouts/_navbar.html.erb
<nav class="navcolor" role="navigation">
  <%= link_to "SellStuff", root_path, class:"brand-logo", id:"logo-container", style:"padding-left: 10px;" %>
  <div class="nav-wrapper container">
    <div class="left-links" style="padding-left: 30px;">
      <ul class=" hide-on-med-and-down">
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
    </div>
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
      <a class="dropdown-button btn" style="background-color: #808080 !important;" href="#" data-activates="dropdown1">
        <div id="dropD" style="color: #ffffff;">Settings</div></a>
      <ul id="dropdown1" class="dropdown-content">
        <li><%= link_to "Bought", purchases_path %></li>
        <li><%= link_to "Sold", sales_path %></li>
        <li><%= link_to "Listings", seller_path %></li>
        <li><%= link_to "Profile", edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>

    <ul id="nav-mobile" class="side-nav">
      <li><%= link_to "About", root_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "Purchase History", purchases_path %></li>
      <li><%= link_to "Sales History", sales_path %></li>
      <li><%= link_to "Manage Listings", seller_path %></li>
      <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/header' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, html: { multipart: true }) do |f| %>
<% if @listing.errors.any? %>
  <div id="card-alert" class="card red lighten-5">
    <div class="card-content red-text">
      <h5><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h5>
    </div>
    <ul>
    <% @listing.errors.full_messages.each do |message| %>
      <li style="padding-left: 30px; padding-bottom: 20px;"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="stripe_error" style="display: none;">
  <noscript>Javascript needs to beenabled!</noscript>
</div>

<div class="row">
  <form class="col s12">
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
        <%= f.text_field :name, id:"icon_prefix", class:"validate" %>
        <%= f.label :name %>
      </div>
    </div>

    <div class="row">
        <div class="input-field col s3">
          <i class="material-icons prefix">toll</i>
          <%= f.text_field :price, id:"icon_prefix", class:"validate" %>
          <%= f.label :price %>
        </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">description</i>
        <%= f.text_area :description, id:"icon_prefix", class:"materialize-textarea" %>
        <%= f.label :description %>
      </div>
    </div>

    <div class="row">
      <div class="col s6">
        <form action="#">
          <div class="file-field input-field">
            <div class="btn">
                <i class="material-icons right">file_upload</i>Image
              <input type="file" name="listing[image]" id="listing_image" multiple />
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text" placeholder="Upload one or more files">
            </div>
          </div>
        </form>
      </div>
    </div>

    <h3>Bank Account Info</h3>

    <div class="row">
        <div class="input-field col s3">
          <%= text_field_tag :country, nil, { name: nil, 'data-stripe': "country", class:"validate"} %>
          <%= label_tag :country %>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s3">
          <%= text_field_tag :routing_number, nil, { name: nil, 'data-stripe': "routingNumber", class:"validate"} %>
          <%= label_tag :routing_number %>
        </div>
    </div>
    <div class="row">
        <div class="input-field col s3">
          <%= text_field_tag :account_number, nil, { name: nil, 'data-stripe': "accountNumber", class:"validate"} %>
          <%= label_tag :account_number %>
        </div>
    </div>

    <div class="row">
      <div class="col s6">
        <button class="btn waves-effect buttoncolor" type="submit" name="action">Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>

  </form>
</div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>


<%= link_to 'Show', @listing, class:"waves-effect waves-teal btn-flat" %> |
<%= link_to 'Back', listings_path, class:"waves-effect waves-teal btn-flat" %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center black-text">2nd-hand items <br> from around the world.</h1>
    <div class="row center">
      <h5 class="header col s12 light">Discover one-of-a-kind items.</h5>
    </div>
  </div>
</div>

  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col s12 m6 l3">
        <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <%= link_to image_tag(listing.image_url), listing, class:"activator" %>
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= link_to "#{listing.name}", listing %><br><%= number_to_currency(listing.price) %><i class="material-icons right">more_vert</i></span>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= link_to "#{listing.name}", listing %><i class="material-icons right">close</i></span>
            <p>Seller: <%= listing.user.name %></p>
            <p><%= listing.description %></p>
          </div>
        </div>
      </div>
    <% end %>
    </div>


<br>

<% if user_signed_in? %>
  <a href="<%= new_listing_path %>", class="btn-floating btn-large waves-effect waves-light">
    <i class="material-icons">add</i>
  </a>
<% end %>

app/views/listings/new.html.erb
<h3>New Listing</h3>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class:"waves-effect waves-teal btn-flat" %>

app/views/listings/seller.html.erb
  <table class="striped bordered responsive-table">
    <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th style="text-align: center;">Actions</th>
    </tr>

    <% @listings.each do |listing| %>
      <tr>
        <td><%= image_tag listing.image.url, class:"sellerImage" %></td>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= number_to_currency(listing.price) %></td>
        <td style="text-align: center;">
          <a class="dropdown-button btn buttoncolor" href="#" data-activates="dropdown2"><i class="material-icons">menu</i></a>
          <ul id="dropdown2" class="dropdown-content">
            <li><%= link_to 'View', listing %></li>
            <li><%= link_to 'Edit', edit_listing_path(listing) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' }, style:"color: red;" %></li>
          </ul>
        <td>
      </tr>
    <% end %>
  </table>


<br>
<a href="<%= new_listing_path %>", class="btn-floating btn-large waves-effect waves-light">
  <i class="material-icons">add</i>
</a>Create Listing

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col s12 m6">
    <div class="card large">
        <%= image_tag @listing.image_url %>
      </div>
    </div>
  <div class="col s12 m6">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %>
    <p>Description: <%= @listing.description %></p>
    <br>
    <%= link_to "Buy It Now", new_listing_order_path(@listing), class:"btn waves-effect buttoncolor" %>
  </div>
</div>

<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class:"waves-effect waves-teal btn-flat" %> |
<% end %>
  <%= link_to 'Back', listings_path, class:"waves-effect waves-teal btn-flat" %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col s4">
  </div>
  <div class="col s8">
    <h3 style="color: #9e9e9e;">Order Form</h3>
  </div>
</div>
<div class="row">
  <div class="col s4">
    <%= image_tag @listing.image.url, id:"orderImage" %>
    <h4><%= @listing.name %></h4>
    <h5><%= number_to_currency(@listing.price) %></h5>
  </div>
  <div class="col s8">
    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="card-alert" class="card red lighten-5">
          <div class="card-content red-text">
            <h5><%= pluralize(@order.errors.count, "error") %> prohibited this listing from being saved:</h5>
          </div>
          <ul>
            <% @order.errors.full_messages.each do |message| %>
              <li style="padding-left: 30px; padding-bottom: 20px;"><%= message %></li>
              <li> <span class="payola-payment-error"></span></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>

      <div class="field">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>

      <div class="field">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>

      <div class="field">
            <%= label_tag :email, "Email for receipt" %>
            <%= text_field_tag :email, nil, { name: nil, 'data-stripe': "email" } %>
      </div>
      <div class="row">
        <div class="col s8 field">
          <%= label_tag :card_number, "Credit Card Number" %>
          <%= text_field_tag :card_number, nil, { name: nil, 'data-stripe': "number" } %>
        </div>
        <div class="col s4 field">
          <%= label_tag :card_code, "CVC" %>
          <%= text_field_tag :card_code, nil, { name: nil, 'data-stripe': "cvc" } %>
        </div>
      </div>
      <%= label_tag nil, "Expiration Date" %>
      <div class="row">
        <div class="input-field col s3">
          <%= select_month nil, { use_two_digit_numbers: true },  {name: nil, 'data-stripe': "exp-month"} %>
        </div>
        <div class="input-field col s3">
          <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, {name: nil, 'data-stripe': "exp-year"} %>
        </div>
      </div>

      <div class="btn waves-effect buttoncolor">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path, class:"waves-effect waves-teal btn-flat" %>

app/views/orders/purchases.html.erb
<div class="center">
  <h3>Purchase History</h3>
</div>
  <table class="striped bordered responsive-table">
    <tr>
        <th>Image</th>
        <th>Item</th>
        <th>Price</th>
        <th>Seller</th>
        <th>Date Purchased</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td><%= image_tag order.listing.image.url, class:"sellerImage" %></td>
        <td><%= order.listing.name %></td>
        <td><%= number_to_currency(order.listing.price) %></td>
        <td><%= order.seller.name %></td>
        <td><%= order.created_at.strftime("%B %-d, %Y") %>
      </tr>
    <% end %>
  </table>

app/views/orders/sales.html.erb
<div class="center">
  <h3>Sales History</h3>
</div>
  <table class="striped bordered responsive-table">
    <tr>
        <th>Image</th>
        <th>Item</th>
        <th>Price</th>
        <th>Customer</th>
        <th>Date Sold</th>
    </tr>

    <% @orders.each do |order| %>
      <tr>
        <td><%= image_tag order.listing.image.url, class:"sellerImage" %></td>
        <td><%= order.listing.name %></td>
        <td><%= number_to_currency(order.listing.price) %></td>
        <td><%= order.buyer.name %></td>
        <td><%= order.created_at.strftime("%B %-d, %Y") %>
      </tr>
    <% end %>
  </table>

app/views/pages/about.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center red-text">About</h1>
    <div class="row center">
      <h5 class="header col s12 light">This is SellStuff. An easy-to-use marketplace for anything you'd like to buy, sell, or ponder!</h5>
    </div>
    <div class="row center">
      <a href="<%= new_listing_path %>", class="btn-floating btn-large waves-effect waves-light red">
        <i class="material-icons">add</i>
      </a>
    </div>
    <br><br>

  </div>
</div>


  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Speeds up development</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">User Experience Focused</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div>

  </div>
  <br><br>

  <div class="section">

  </div>
</div>




<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="js/materialize.js"></script>
<script src="js/init.js"></script>

app/views/pages/contact.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center red-text">Contact</h1>
    <div class="row center">
      <h5 class="header col s12 light">email jon.corrin@gmail.com for more information</h5>
    </div>
    <div class="row center">
      <a href="<%= new_listing_path %>", class="btn-floating btn-large waves-effect waves-light red">
        <i class="material-icons">add</i>
      </a>
    </div>
    <br><br>

  </div>
</div>

  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">Speeds up development</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
          <h5 class="center">User Experience Focused</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div>

  </div>
  <br><br>

  <div class="section">

  </div>
</div>




<!--  Scripts-->
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="js/materialize.js"></script>
<script src="js/init.js"></script>